// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exec.proto

package com.rnctech.nrdataservice.proto;

public interface CompletionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rn.CompletionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>int32 cursor = 2;</code>
   * @return The cursor.
   */
  int getCursor();
}
