// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exec.proto

package com.rnctech.nrdataservice.proto;

/**
 * Protobuf type {@code rn.CompletionResponse}
 */
public final class CompletionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rn.CompletionResponse)
    CompletionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompletionResponse.newBuilder() to construct.
  private CompletionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompletionResponse() {
    matches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompletionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CompletionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              matches_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            matches_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        matches_ = matches_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rnctech.nrdataservice.proto.ExecProto.internal_static_rn_CompletionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rnctech.nrdataservice.proto.ExecProto.internal_static_rn_CompletionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rnctech.nrdataservice.proto.CompletionResponse.class, com.rnctech.nrdataservice.proto.CompletionResponse.Builder.class);
  }

  public static final int MATCHES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList matches_;
  /**
   * <code>repeated string matches = 1;</code>
   * @return A list containing the matches.
   */
  public com.google.protobuf.ProtocolStringList
      getMatchesList() {
    return matches_;
  }
  /**
   * <code>repeated string matches = 1;</code>
   * @return The count of matches.
   */
  public int getMatchesCount() {
    return matches_.size();
  }
  /**
   * <code>repeated string matches = 1;</code>
   * @param index The index of the element to return.
   * @return The matches at the given index.
   */
  public java.lang.String getMatches(int index) {
    return matches_.get(index);
  }
  /**
   * <code>repeated string matches = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the matches at the given index.
   */
  public com.google.protobuf.ByteString
      getMatchesBytes(int index) {
    return matches_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < matches_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, matches_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < matches_.size(); i++) {
        dataSize += computeStringSizeNoTag(matches_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMatchesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rnctech.nrdataservice.proto.CompletionResponse)) {
      return super.equals(obj);
    }
    com.rnctech.nrdataservice.proto.CompletionResponse other = (com.rnctech.nrdataservice.proto.CompletionResponse) obj;

    if (!getMatchesList()
        .equals(other.getMatchesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMatchesCount() > 0) {
      hash = (37 * hash) + MATCHES_FIELD_NUMBER;
      hash = (53 * hash) + getMatchesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rnctech.nrdataservice.proto.CompletionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rnctech.nrdataservice.proto.CompletionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rn.CompletionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rn.CompletionResponse)
      com.rnctech.nrdataservice.proto.CompletionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rnctech.nrdataservice.proto.ExecProto.internal_static_rn_CompletionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rnctech.nrdataservice.proto.ExecProto.internal_static_rn_CompletionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rnctech.nrdataservice.proto.CompletionResponse.class, com.rnctech.nrdataservice.proto.CompletionResponse.Builder.class);
    }

    // Construct using com.rnctech.nrdataservice.proto.CompletionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      matches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rnctech.nrdataservice.proto.ExecProto.internal_static_rn_CompletionResponse_descriptor;
    }

    @java.lang.Override
    public com.rnctech.nrdataservice.proto.CompletionResponse getDefaultInstanceForType() {
      return com.rnctech.nrdataservice.proto.CompletionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.rnctech.nrdataservice.proto.CompletionResponse build() {
      com.rnctech.nrdataservice.proto.CompletionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rnctech.nrdataservice.proto.CompletionResponse buildPartial() {
      com.rnctech.nrdataservice.proto.CompletionResponse result = new com.rnctech.nrdataservice.proto.CompletionResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        matches_ = matches_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.matches_ = matches_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rnctech.nrdataservice.proto.CompletionResponse) {
        return mergeFrom((com.rnctech.nrdataservice.proto.CompletionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rnctech.nrdataservice.proto.CompletionResponse other) {
      if (other == com.rnctech.nrdataservice.proto.CompletionResponse.getDefaultInstance()) return this;
      if (!other.matches_.isEmpty()) {
        if (matches_.isEmpty()) {
          matches_ = other.matches_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMatchesIsMutable();
          matches_.addAll(other.matches_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rnctech.nrdataservice.proto.CompletionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rnctech.nrdataservice.proto.CompletionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList matches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMatchesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        matches_ = new com.google.protobuf.LazyStringArrayList(matches_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @return A list containing the matches.
     */
    public com.google.protobuf.ProtocolStringList
        getMatchesList() {
      return matches_.getUnmodifiableView();
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @return The count of matches.
     */
    public int getMatchesCount() {
      return matches_.size();
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @param index The index of the element to return.
     * @return The matches at the given index.
     */
    public java.lang.String getMatches(int index) {
      return matches_.get(index);
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the matches at the given index.
     */
    public com.google.protobuf.ByteString
        getMatchesBytes(int index) {
      return matches_.getByteString(index);
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @param index The index to set the value at.
     * @param value The matches to set.
     * @return This builder for chaining.
     */
    public Builder setMatches(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMatchesIsMutable();
      matches_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @param value The matches to add.
     * @return This builder for chaining.
     */
    public Builder addMatches(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMatchesIsMutable();
      matches_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @param values The matches to add.
     * @return This builder for chaining.
     */
    public Builder addAllMatches(
        java.lang.Iterable<java.lang.String> values) {
      ensureMatchesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, matches_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatches() {
      matches_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matches = 1;</code>
     * @param value The bytes of the matches to add.
     * @return This builder for chaining.
     */
    public Builder addMatchesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMatchesIsMutable();
      matches_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rn.CompletionResponse)
  }

  // @@protoc_insertion_point(class_scope:rn.CompletionResponse)
  private static final com.rnctech.nrdataservice.proto.CompletionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rnctech.nrdataservice.proto.CompletionResponse();
  }

  public static com.rnctech.nrdataservice.proto.CompletionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompletionResponse>
      PARSER = new com.google.protobuf.AbstractParser<CompletionResponse>() {
    @java.lang.Override
    public CompletionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompletionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CompletionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompletionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rnctech.nrdataservice.proto.CompletionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

