// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exec.proto

package com.rnctech.nrdataservice.proto;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rn.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rn.IPythonStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.rn.IPythonStatus status = 1;</code>
   * @return The status.
   */
  com.rnctech.nrdataservice.proto.IPythonStatus getStatus();
}
