// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exec.proto

package com.rnctech.nrdataservice.proto;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rn.StatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
